//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyboardHook01.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyboardHook01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap black_and_white {
            get {
                object obj = ResourceManager.GetObject("black_and_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blue {
            get {
                object obj = ResourceManager.GetObject("blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream buckling_bs_down {
            get {
                return ResourceManager.GetStream("buckling_bs_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream buckling_bs_up {
            get {
                return ResourceManager.GetStream("buckling_bs_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream buckling_down {
            get {
                return ResourceManager.GetStream("buckling_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream buckling_enter_down {
            get {
                return ResourceManager.GetStream("buckling_enter_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream buckling_enter_up {
            get {
                return ResourceManager.GetStream("buckling_enter_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream buckling_space_down {
            get {
                return ResourceManager.GetStream("buckling_space_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream buckling_space_up {
            get {
                return ResourceManager.GetStream("buckling_space_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream buckling_up {
            get {
                return ResourceManager.GetStream("buckling_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_black_bs_down {
            get {
                return ResourceManager.GetStream("cherry_mx_black_bs_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_black_bs_up {
            get {
                return ResourceManager.GetStream("cherry_mx_black_bs_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_black_down {
            get {
                return ResourceManager.GetStream("cherry_mx_black_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_black_enter_down {
            get {
                return ResourceManager.GetStream("cherry_mx_black_enter_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_black_enter_up {
            get {
                return ResourceManager.GetStream("cherry_mx_black_enter_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_black_space_down {
            get {
                return ResourceManager.GetStream("cherry_mx_black_space_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_black_space_up {
            get {
                return ResourceManager.GetStream("cherry_mx_black_space_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_black_up {
            get {
                return ResourceManager.GetStream("cherry_mx_black_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_blue_down {
            get {
                return ResourceManager.GetStream("cherry_mx_blue_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_blue_up {
            get {
                return ResourceManager.GetStream("cherry_mx_blue_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_brown_bs_down {
            get {
                return ResourceManager.GetStream("cherry_mx_brown_bs_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_brown_bs_up {
            get {
                return ResourceManager.GetStream("cherry_mx_brown_bs_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_brown_down {
            get {
                return ResourceManager.GetStream("cherry_mx_brown_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_brown_enter_down {
            get {
                return ResourceManager.GetStream("cherry_mx_brown_enter_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_brown_enter_up {
            get {
                return ResourceManager.GetStream("cherry_mx_brown_enter_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_brown_space_down {
            get {
                return ResourceManager.GetStream("cherry_mx_brown_space_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_brown_space_up {
            get {
                return ResourceManager.GetStream("cherry_mx_brown_space_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_brown_up {
            get {
                return ResourceManager.GetStream("cherry_mx_brown_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_green_down {
            get {
                return ResourceManager.GetStream("cherry_mx_green_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_green_up {
            get {
                return ResourceManager.GetStream("cherry_mx_green_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_red_down {
            get {
                return ResourceManager.GetStream("cherry_mx_red_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_red_silence_down {
            get {
                return ResourceManager.GetStream("cherry_mx_red_silence_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_red_silence_up {
            get {
                return ResourceManager.GetStream("cherry_mx_red_silence_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_red_up {
            get {
                return ResourceManager.GetStream("cherry_mx_red_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_silence_black_down {
            get {
                return ResourceManager.GetStream("cherry_mx_silence_black_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_silence_black_up {
            get {
                return ResourceManager.GetStream("cherry_mx_silence_black_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_silver_down {
            get {
                return ResourceManager.GetStream("cherry_mx_silver_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream cherry_mx_silver_up {
            get {
                return ResourceManager.GetStream("cherry_mx_silver_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cyan {
            get {
                object obj = ResourceManager.GetObject("cyan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;text&gt;
        ///	&lt;string name=&quot;program_title&quot;&gt;K+&lt;/string&gt;
        ///	
        ///	&lt;string name=&quot;menu_file&quot;&gt;File&lt;/string&gt;
        ///	&lt;string name=&quot;save&quot;&gt;Save&lt;/string&gt;
        ///	&lt;string name=&quot;exit&quot;&gt;Exit&lt;/string&gt;
        ///	
        ///	&lt;string name=&quot;menu_mode&quot;&gt;Mode&lt;/string&gt;
        ///	&lt;string name=&quot;mode_total&quot;&gt;Total Keystrokes&lt;/string&gt;
        ///	&lt;string name=&quot;mode_current&quot;&gt;Current Keystrokes&lt;/string&gt;
        ///	&lt;string name=&quot;mode_test&quot;&gt;Keyborad Test&lt;/string&gt;
        ///	
        ///	&lt;string name=&quot;menu_preference&quot;&gt;Preference&lt;/string&gt;
        ///	&lt;string name=&quot;language&quot;&gt;Language&lt;/strin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap green {
            get {
                object obj = ResourceManager.GetObject("green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap half_rainbow {
            get {
                object obj = ResourceManager.GetObject("half_rainbow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style&gt;
        ///            .warning {
        ///                background-color: #fff7ae;
        ///                border-radius: 15px;
        ///                padding: 20px;
        ///            }
        ///            .tip {
        ///                background-color: #b4ffba;
        ///                border-radius: 15px;
        ///                padding: 20px;
        ///            }
        ///            .title {
        ///                font-weight: bold;
        ///                font-size: 24px;
        ///            }
        ///            .question {
        ///                font-wei [rest of string was truncated]&quot;;.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style&gt;
        ///            .warning {
        ///                background-color: #fff7ae;
        ///                border-radius: 15px;
        ///                padding: 20px;
        ///            }
        ///            .tip {
        ///                background-color: #b4ffba;
        ///                border-radius: 15px;
        ///                padding: 20px;
        ///            }
        ///            .title {
        ///                font-weight: bold;
        ///                font-size: 24px;
        ///            }
        ///            .question {
        ///                font-wei [rest of string was truncated]&quot;;.
        /// </summary>
        public static string help_cn {
            get {
                return ResourceManager.GetString("help_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream holy_bs_down {
            get {
                return ResourceManager.GetStream("holy_bs_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream holy_bs_up {
            get {
                return ResourceManager.GetStream("holy_bs_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream holy_down {
            get {
                return ResourceManager.GetStream("holy_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream holy_enter_down {
            get {
                return ResourceManager.GetStream("holy_enter_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream holy_enter_up {
            get {
                return ResourceManager.GetStream("holy_enter_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream holy_space_down {
            get {
                return ResourceManager.GetStream("holy_space_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream holy_space_up {
            get {
                return ResourceManager.GetStream("holy_space_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream holy_up {
            get {
                return ResourceManager.GetStream("holy_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ink_bs_down {
            get {
                return ResourceManager.GetStream("ink_bs_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ink_bs_up {
            get {
                return ResourceManager.GetStream("ink_bs_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ink_down {
            get {
                return ResourceManager.GetStream("ink_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ink_enter_down {
            get {
                return ResourceManager.GetStream("ink_enter_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ink_enter_up {
            get {
                return ResourceManager.GetStream("ink_enter_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ink_space_down {
            get {
                return ResourceManager.GetStream("ink_space_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ink_space_up {
            get {
                return ResourceManager.GetStream("ink_space_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ink_up {
            get {
                return ResourceManager.GetStream("ink_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream kailh_bs_down {
            get {
                return ResourceManager.GetStream("kailh_bs_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream kailh_bs_up {
            get {
                return ResourceManager.GetStream("kailh_bs_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream kailh_down {
            get {
                return ResourceManager.GetStream("kailh_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream kailh_enter_down {
            get {
                return ResourceManager.GetStream("kailh_enter_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream kailh_enter_up {
            get {
                return ResourceManager.GetStream("kailh_enter_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream kailh_space_down {
            get {
                return ResourceManager.GetStream("kailh_space_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream kailh_space_up {
            get {
                return ResourceManager.GetStream("kailh_space_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream kailh_up {
            get {
                return ResourceManager.GetStream("kailh_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap keyplus_pic {
            get {
                object obj = ResourceManager.GetObject("keyplus_pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon logo64 {
            get {
                object obj = ResourceManager.GetObject("logo64", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap magenta {
            get {
                object obj = ResourceManager.GetObject("magenta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream novelkeys_bs_down {
            get {
                return ResourceManager.GetStream("novelkeys_bs_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream novelkeys_bs_up {
            get {
                return ResourceManager.GetStream("novelkeys_bs_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream novelkeys_down {
            get {
                return ResourceManager.GetStream("novelkeys_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream novelkeys_enter_down {
            get {
                return ResourceManager.GetStream("novelkeys_enter_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream novelkeys_enter_up {
            get {
                return ResourceManager.GetStream("novelkeys_enter_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream novelkeys_space_down {
            get {
                return ResourceManager.GetStream("novelkeys_space_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream novelkeys_space_up {
            get {
                return ResourceManager.GetStream("novelkeys_space_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream novelkeys_up {
            get {
                return ResourceManager.GetStream("novelkeys_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rainbow {
            get {
                object obj = ResourceManager.GetObject("rainbow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red {
            get {
                object obj = ResourceManager.GetObject("red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream skcm_bs_down {
            get {
                return ResourceManager.GetStream("skcm_bs_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream skcm_bs_up {
            get {
                return ResourceManager.GetStream("skcm_bs_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream skcm_down {
            get {
                return ResourceManager.GetStream("skcm_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream skcm_enter_down {
            get {
                return ResourceManager.GetStream("skcm_enter_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream skcm_enter_up {
            get {
                return ResourceManager.GetStream("skcm_enter_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream skcm_space_down {
            get {
                return ResourceManager.GetStream("skcm_space_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream skcm_space_up {
            get {
                return ResourceManager.GetStream("skcm_space_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream skcm_up {
            get {
                return ResourceManager.GetStream("skcm_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream topre_bs_down {
            get {
                return ResourceManager.GetStream("topre_bs_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream topre_bs_up {
            get {
                return ResourceManager.GetStream("topre_bs_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream topre_down {
            get {
                return ResourceManager.GetStream("topre_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream topre_enter_down {
            get {
                return ResourceManager.GetStream("topre_enter_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream topre_enter_up {
            get {
                return ResourceManager.GetStream("topre_enter_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream topre_space_down {
            get {
                return ResourceManager.GetStream("topre_space_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream topre_space_up {
            get {
                return ResourceManager.GetStream("topre_space_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream topre_up {
            get {
                return ResourceManager.GetStream("topre_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream turquoise_bs_down {
            get {
                return ResourceManager.GetStream("turquoise_bs_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream turquoise_bs_up {
            get {
                return ResourceManager.GetStream("turquoise_bs_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream turquoise_down {
            get {
                return ResourceManager.GetStream("turquoise_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream turquoise_enter_down {
            get {
                return ResourceManager.GetStream("turquoise_enter_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream turquoise_enter_up {
            get {
                return ResourceManager.GetStream("turquoise_enter_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream turquoise_space_down {
            get {
                return ResourceManager.GetStream("turquoise_space_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream turquoise_space_up {
            get {
                return ResourceManager.GetStream("turquoise_space_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream turquoise_up {
            get {
                return ResourceManager.GetStream("turquoise_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to did|hand|what|more|mane|school|being|for|many|who|sentence|talk|example|too|found|mountain|was|girl|paper|its|four|which|answer|might|said|song|under|it|word|each|walk|once|your|country|stop|most|kind|so|father|grow|we|than|little|go|tell|been|as|had|men|question|head|learn|be|does|or|number|because|also|life|later|children|state|us|far|if|good|very|never|picture|night|city|story|should|make|water|leave|saw|one|turn|me|great|come|went|something|read|idea|side|has|sometimes|follow|then|eat|again|think|carry| [rest of string was truncated]&quot;;.
        /// </summary>
        public static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to politic|untoward|overwrought|lush|suppress|clement|dormant|discombobulate|dart|phlegmatic|corrugated|instate|grimace|default|tackle|talisman|garish|sound|hangdog|budge|remodel|baffling|nitpick|sober|mendacious|hallucination|homogenize|grueling|desperate|anecdote|eulogy|renounce|blemish|extrovert|mesmerize|meager|hirsute|scuff|domicile|complementary|parrot|propitiate|stratify|chagrin|remnant|collapse|weigh|misapprehension|rickety|peel|laborious|clarion|fiasco|edifice|mint|mournful|crave|moratorium|pandemic|s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string words_gmat {
            get {
                return ResourceManager.GetString("words_gmat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revenge|noisome|nicety|babble|iconoclast|tout|instigate|aleck|lavish|palatable|palter|extant|prudish|arabesque|vitiate|imprecation|glossy|slack|random|release|excrete|obtrusive|muffle|homely|stray|protocol|rambunctious|topple|inherent|amorphous|pathological|ostracism|pundit|rigmarole|heartrending|discomfit|cordon|breach|picaresque|perspicacious|bonhomie|nuance|disingenuous|aphorism|rubicund|beholden|imperative|undergird|jabber|iniquity|unwitting|condemn|credulity|idolatrize|transgress|bifurcate|ensue|debili [rest of string was truncated]&quot;;.
        /// </summary>
        public static string words_gre {
            get {
                return ResourceManager.GetString("words_gre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anticlimax|wretchedness|pandemic|broach|overdo|esquire|advent|deify|monograph|lingual|moratorium|maize|finery|proffer|bask|mendacious|supplementary|afoot|demerit|privilege|collapse|absence|brigand|torpor|distiller|vacillate|impious|foot-note|audition|contribute|tantalize|fervor|slight|advertiser|promontory|distillation|physique|abusive|emancipate|encyclical|irreducible|improvident|ravenous|recede|overstride|anathema|normalcy|taut|cantonment|tyrannical|commitment|gyroscope|immovable|amorous|barometer|infidel [rest of string was truncated]&quot;;.
        /// </summary>
        public static string words_toefl {
            get {
                return ResourceManager.GetString("words_toefl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April|either|Los|oil|II|business|machines|provide|eight|particularly|lines|Last|working|specific|television|shows|exchange|thing|currently|seven|sell|strategy|plans|very|she|language|general|possible|For|found|well|requires|both|own|application|cars|book|water|until|since|seems|Monday|nearly|around|told|Calif|received|share|money|interface|set|offers|between|cent|Unix|developed|growing|San|multiple|businesses|children|women|believe|features|let|board|project|tools|before|we|black|directly|Other|killed|This| [rest of string was truncated]&quot;;.
        /// </summary>
        public static string words_top_1000 {
            get {
                return ResourceManager.GetString("words_top_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of|my|well|move|answer|air|still|say|men|family|cut|through|home|quickly|mother|come|do|list|together|even|tell|next|show|young|out|quite|head|new|question|all|after|who|place|again|add|open|to|water|close|it&apos;s|in|make|once|last|did|carry|near|world|her|don&apos;t|here|few|when|now|both|is|too|man|write|call|house|America|if|another|second|song|play|being|were|any|tree|big|back|than|had|me|while|see|first|for|this|not|plant|important|food|these|later|which|sometimes|where|two|you|day|always|that|quick|never|away [rest of string was truncated]&quot;;.
        /// </summary>
        public static string words_top_200 {
            get {
                return ResourceManager.GetString("words_top_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap yellow {
            get {
                object obj = ResourceManager.GetObject("yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;text&gt;
        ///	&lt;string name=&quot;program_title&quot;&gt;K+&lt;/string&gt;
        ///
        ///	&lt;string name=&quot;menu_file&quot;&gt;文件&lt;/string&gt;
        ///	&lt;string name=&quot;save&quot;&gt;保存&lt;/string&gt;
        ///	&lt;string name=&quot;exit&quot;&gt;退出&lt;/string&gt;
        ///
        ///	&lt;string name=&quot;menu_mode&quot;&gt;模式&lt;/string&gt;
        ///	&lt;string name=&quot;mode_total&quot;&gt;总共按键次数&lt;/string&gt;
        ///	&lt;string name=&quot;mode_current&quot;&gt;本次按键次数&lt;/string&gt;
        ///	&lt;string name=&quot;mode_test&quot;&gt;键盘测试&lt;/string&gt;
        ///
        ///	&lt;string name=&quot;menu_preference&quot;&gt;偏好&lt;/string&gt;
        ///	&lt;string name=&quot;language&quot;&gt;语言&lt;/string&gt;
        ///	&lt;string name=&quot;english&quot;&gt;英语&lt;/string&gt;
        ///	&lt;string name=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string zh_CN {
            get {
                return ResourceManager.GetString("zh_CN", resourceCulture);
            }
        }
    }
}
